#cloud-config
write_files:
  - path: "/usr/local/etc/startup.sh"
    permissions: "755"
    content: |
      #!/bin/bash

      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
    defer: true
runcmd:
  - ["/usr/local/etc/startup.sh"]
